# AUTO-GENERATED by generate_config_from_docs.py
from pathlib import Path

# Base project directory: CapstoneOCR/
BASE_DIR = Path(__file__).resolve().parent.parent

# Folder with your PDFs
DOCS_DIR = BASE_DIR / 'docs'

# List of documents discovered in DOCS_DIR
DOCS = [
    {
        'doc_id': '3d-reconstructions-uav',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / '3D Reconstructions UAV.pdf',
    },
    {
        'doc_id': '6-12',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / '6-12.pdf',
    },
    {
        'doc_id': 'ai-and-procurement-primer-summer-2021',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'AI and Procurement Primer Summer 2021.pdf',
    },
    {
        'doc_id': 'access-and-interconnection-pricing',
        'type': 'ocr-pdf',
        'pdf_path': DOCS_DIR / 'Access and Interconnection Pricing.pdf',
    },
    {
        'doc_id': 'ageism-in-the-family-2022-final',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Ageism in the Family 2022 Final.pdf',
    },
    {
        'doc_id': 'angles-and-distance-effect-on-3d-reconstructions',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Angles and Distance Effect on 3D Reconstructions.pdf',
    },
    {
        'doc_id': 'ceri-2018',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'CERI 2018.pdf',
    },
    {
        'doc_id': 'conbuildmat-d-16-00279',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'CONBUILDMAT D-16 00279.pdf',
    },
    {
        'doc_id': 'covid-19-modeling-call-july-15',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'COVID-19 Modeling Call July 15.pdf',
    },
    {
        'doc_id': 'dbscan-v25-jcce',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'DBSCAN v25 JCCE.pdf',
    },
    {
        'doc_id': 'dcase-2019-workshop-lipping',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'DCASE 2019 Workshop Lipping.pdf',
    },
    {
        'doc_id': 'fin-01-066',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'FIN 01 066.pdf',
    },
    {
        'doc_id': 'geotech-faculty-snapshot',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Geotech Faculty Snapshot.pdf',
    },
    {
        'doc_id': 'gonzales-2024-chai-addressing-inequities',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Gonzales 2024 CHAI Addressing Inequities.pdf',
    },
    {
        'doc_id': 'guenfoud-et-al-2017',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Guenfoud et al 2017.pdf',
    },
    {
        'doc_id': 'guiness-bridge-open-repo',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Guiness Bridge Open Repo.pdf',
    },
    {
        'doc_id': 'hpd-ustdc-80',
        'type': 'ocr-pdf',
        'pdf_path': DOCS_DIR / 'HPD USTDC 80.pdf',
    },
    {
        'doc_id': 'iabse-vancouver-2017-proceedings',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'IABSE Vancouver 2017 Proceedings.pdf',
    },
    {
        'doc_id': 'jars-16969-online',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'JARS 16969 Online.pdf',
    },
    {
        'doc_id': 'mortar-sahc',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Mortar SAHC.pdf',
    },
    {
        'doc_id': 'nsf-workshop-report-jan-12-2006',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'NSF Workshop Report Jan 12 2006.pdf',
    },
    {
        'doc_id': 'nyu-avoid-second-wave-overview',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'NYU Avoid Second Wave Overview.pdf',
    },
    {
        'doc_id': 'nyu-model-overview',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'NYU Model Overview.pdf',
    },
    {
        'doc_id': 'negative-stiffness-in-concrete-beams',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Negative Stiffness in Concrete Beams.pdf',
    },
    {
        'doc_id': 'oculus-rift-application-for-training-drone-pilots',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Oculus Rift Application for Training Drone Pilots.pdf',
    },
    {
        'doc_id': 'productive-aging-gender-dec-2021',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Productive Aging Gender Dec 2021.pdf',
    },
    {
        'doc_id': 'recruitment-brief-diverse-older-adults-feb-23',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Recruitment Brief Diverse Older Adults Feb 23.pdf',
    },
    {
        'doc_id': 'road-features-als-data',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Road Features ALS Data.pdf',
    },
    {
        'doc_id': 'scda-chemical-open-report-(1)',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'SCDA Chemical Open Report (1).pdf',
    },
    {
        'doc_id': 'scda-chemical-open-report',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'SCDA Chemical Open Report.pdf',
    },
    {
        'doc_id': 'soa-tres',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'SOA Tres.pdf',
    },
    {
        'doc_id': 'shadow-probability-theory-jan-2012',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'Shadow Probability Theory Jan 2012.pdf',
    },
    {
        'doc_id': 'uavbridge-openrepo',
        'type': 'pdf',
        'pdf_path': DOCS_DIR / 'UAVBridge OpenRepo.pdf',
    },
]
