from pathlib import Path

def main():
    # Base project directory: CapstoneOCR/
    base_dir = Path(__file__).resolve().parent.parent
    docs_dir = base_dir / "docs"
    config_path = base_dir / "code" / "config_docs.py"

    # List the PDFs that require OCR instead of standard text extraction.
    # Add file names exactly as they appear in the docs/ folder.
    ocr_required = {
        # Example: "scanned_report.pdf",
    }

    if not docs_dir.exists():
        raise FileNotFoundError(f"Docs folder not found at: {docs_dir}")

    pdf_files = sorted(docs_dir.glob("*.pdf"))
    if not pdf_files:
        raise FileNotFoundError(f"No PDF files found in: {docs_dir}")

    # Build DOCS entries
    docs_entries = []
    for pdf in pdf_files:
        # doc_id = filename without extension, spaces -> '-', lowercased
        doc_id = pdf.stem.replace(" ", "-").lower()
        doc_type = "ocr-pdf" if pdf.name in ocr_required else "pdf"
        entry = (
            "    {\n"
            f"        'doc_id': '{doc_id}',\n"
            f"        'type': '{doc_type}',\n"
            f"        'pdf_path': DOCS_DIR / '{pdf.name}',\n"
            "    },"
        )
        docs_entries.append(entry)

    docs_block = "\n".join(docs_entries)

    # Full config_docs.py content
    config_source = f"""# AUTO-GENERATED by generate_config_from_docs.py
from pathlib import Path

# Base project directory: CapstoneOCR/
BASE_DIR = Path(__file__).resolve().parent.parent

# Folder with your PDFs
DOCS_DIR = BASE_DIR / 'docs'

# List of documents discovered in DOCS_DIR
DOCS = [
{docs_block}
]
"""

    config_path.write_text(config_source, encoding="utf-8")
    print(f"Wrote config for {len(pdf_files)} PDFs to {config_path}")


if __name__ == "__main__":
    main()